### ISSUE TITLE
支付后没有给出key

### ISSUE THREAD

**Issue by Watee22** [fatwang2/sum4all#100]
![微信图片_20241221143143](https://github.com/user-attachments/assets/465ae519-86dd-4c0b-acd6-da4b1d28484d)
![微信图片_20241221143148](https://github.com/user-attachments/assets/8d4def2a-4ac6-4357-8dbc-ae5763c421ee)
在付费后额度没有增加

**Comment by fatwang2** [comment]
现在应该收到了吧，看了下是邮件服务挂了
