### ISSUE TITLE
是否可以与链接内容继续聊天？

### ISSUE THREAD

**Issue by Payne-Wang** [fatwang2/sum4all#12]
如果我想进一步根据链接内容向机器人进行询问，该如何操作？就像chatPDF那样子，谢谢大佬！

**Comment by fatwang2** [comment]
目前没支持，主要没想好比较好的处理，继续沟通与不继续沟通两种场景，目前看到的解决方案主要是让用户输入是否开启对话，你有好的想法也可以提

Payne-Wang ***@***.***>于2023年11月21日 周二11:37写道：

**Comment by Payne-Wang** [comment]
linkai有类似的功能，不知道能不能用在这边🤔🤔![IMG_20231121_233724.jpg](https://github.com/fatwang2/sum4all/assets/44337721/e3390301-0c00-48c1-a47a-cba0d3e3eb05)

**Comment by fatwang2** [comment]
已经实现了，可以更新体验下

**Comment by Payne-Wang** [comment]
大佬太优秀！点赞！

**Comment by fatwang2** [comment]
欢迎反馈，欢迎加 telegram 群哈
