### ISSUE TITLE
群聊中是否可以通过引用某张图片或者通过某个关键词触发识图

### ISSUE THREAD

**Issue by davexxx1214** [fatwang2/sum4all#17]
每次发送图片就触发识图，在群聊场合非常不友好。
请问是否可以支持通过引用某张图片或者通过某个关键词触发识图？

**Comment by fatwang2** [comment]
新版本支持群聊开关了，如果感觉打扰可以直接把群聊开关关掉。群聊里的触发指令，感觉用起来有点复杂，等想到更好的方案再改
