### ISSUE TITLE
重启容器后插件识别不到

### ISSUE THREAD

**Issue by biaozhang64** [fatwang2/sum4all#19]
想问下为什么我每次重启[chatgpt-on-wechat插件就没了呢，#plist列表里没有这个插件，得重新下。而且下完还需要去bash里手动安装requirements才能检测到。
我是群辉nas docker安装的

**Comment by fatwang2** [comment]
docker 安装的，插件没有持久化，都需要重新安装的，你其他三方插件也一样吧，另外安装的时候用#installp的管理员命令，会自动安装依赖

biaozhang64 ***@***.***>于2023年12月8日 周五08:43写道：
