### ISSUE TITLE
报错，mac下直接clone的

### ISSUE THREAD

**Issue by xinggonglie** [fatwang2/sum4all#21]
![Screenshot_2023-12-09-06-59-58-821_com.tencent.mm-edit.jpg](https://github.com/fatwang2/sum4all/assets/109005556/46fbcc07-a083-4542-904f-fa5d5370320d)

**Comment by fatwang2** [comment]
是想说有时候会失败？我看你第二条是成功的。 第一条失败的如果再发一遍，还是失败吗

**Comment by xinggonglie** [comment]
使用sgcc的网址http://www.sgcc.com.cn/html/sgcc_main/index.shtml，一直报错
第二个网址没问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月9日(周六) 上午8:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [fatwang2/sum4all] 报错，mac下直接clone的 (Issue #21)




 
是想说有时候会失败？我看你第二条是成功的。 第一条失败的如果再发一遍，还是失败吗

**Comment by fatwang2** [comment]
你这个是首页吧？这有啥好总结的，可能还涉及到了敏感词

xinggonglie ***@***.***>于2023年12月9日 周六08:27写道：
