### ISSUE TITLE
能不能不要这些符号，复制的时候还要一个个修改

### ISSUE THREAD

**Issue by xinggonglie** [fatwang2/sum4all#22]
![Screenshot_2023-12-09-07-02-06-829_com.tencent.mm-edit.jpg](https://github.com/fatwang2/sum4all/assets/109005556/02784dcf-2ca9-4961-9058-8c41e03d151a)

**Comment by fatwang2** [comment]
你看下说明文档，如果是选择 openai 或者 sum4all，你可以自己修改配置文件里的 prompt

**Comment by xinggonglie** [comment]
直接改sum4all.py吗，改完保存就行？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月9日(周六) 上午8:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [fatwang2/sum4all] 能不能不要这些符号，复制的时候还要一个个修改 (Issue #22)




 
你看下说明文档，如果是选择 openai 或者 sum4all，你可以自己修改配置文件里的 prompt

**Comment by fatwang2** [comment]
不需要修改源代码，修改配置文件即可，你看下说明文档

xinggonglie ***@***.***>于2023年12月9日 周六08:30写道：
