### ISSUE TITLE
配置为OpenAI服务导致的500错误问题

### ISSUE THREAD

**Issue by MILKMILKKING** [fatwang2/sum4all#27]
我配置的均是openai，  "sum_service":"openai", 经常会出现：“An error occurred: 500 Server Error: Internal Server Error for url: https://ai.sum4all.site/”
我的openai api平时都很稳定的。

**Comment by fatwang2** [comment]
收到，之前确实也收到过反馈，不知道具体啥原因，我多加点日志看看，有可能是爬取那边不稳定

MILKMILKKING ***@***.***>于2023年12月14日 周四15:11写道：

**Comment by MILKMILKKING** [comment]
之前在研究GPTs action的时候，发现一个API 抓微信文章的网页挺稳的。您能留个邮箱，我发给你吗？

**Comment by fatwang2** [comment]
***@***.***，感谢

MILKMILKKING ***@***.***>于2023年12月15日 周五11:29写道：

**Comment by fatwang2** [comment]
已增加重试逻辑，减少错误情况

**Comment by monk-after-90s** [comment]
> 已增加重试逻辑，减少错误情况

现在又是这个情况了啊
