### ISSUE TITLE
讯飞的图片理解报错

### ISSUE THREAD

**Issue by axyzcc** [fatwang2/sum4all#28]
![68eb775b0ec1cf6512a664b7b93225b](https://github.com/fatwang2/sum4all/assets/102774609/f93fed9a-4463-482a-8b88-0c7803c1d6c1)
这个报错什么问题呢

**Comment by axyzcc** [comment]
重启项目好了

**Comment by fatwang2** [comment]
是的，上个版本不小心动了讯飞的代码，那部分实在太冗杂了，打算后面优化
