### ISSUE TITLE
请问在Docker部署时遇到了找不到libmupdf.so的错误应该如何解决

### ISSUE THREAD

**Issue by Polarbeartnt** [fatwang2/sum4all#29]
在docker中部署了chatgpt-on-wechat，然后使用#installp指令是能够正常完成安装的，但是在#scanp时提示没有发现新的插件，看log发现是找不到libmupdf.so的库文件。配置环境是群晖自带的docker，使用chatgpt-on-wechat上推荐的docker部署方式完成的，具体的log截图见下。
![微信截图_20231221173813](https://github.com/fatwang2/sum4all/assets/62416800/690691ca-4df8-48ba-8310-ab9a911049f9)

**Comment by fatwang2** [comment]
你重启下docker试试？

Yuming Bai ***@***.***>于2023年12月21日 周四17:40写道：
