### ISSUE TITLE
目前似乎仍然只能总结链接，无法总结链接卡片

### ISSUE THREAD

**Issue by MILKMILKKING** [fatwang2/sum4all#3]
你好，目前似乎仍然只能总结链接，无法总结链接卡片。
![image](https://github.com/fatwang2/sum4all/assets/69726213/f83515ec-a84a-41e3-8213-5c1004c88375)

**Comment by fatwang2** [comment]
你要更新下主项目的代码，我亲测是可以的

MILKMILKKING ***@***.***>于2023年9月24日 周日23:15写道：

**Comment by MILKMILKKING** [comment]
你好，我刚刚已经更新了，确认一下：我这个算是更新成功了吗？
![image](https://github.com/fatwang2/sum4all/assets/69726213/02912f63-073d-4592-a8c8-73fa8785f37b)

**Comment by fatwang2** [comment]
是的 看上去项目更新了 接下来配置key就行

**Comment by MILKMILKKING** [comment]
key已经填上了。
还是不行呢。
可以总结链接。但是转发文章过去，没有任何反应呢。

**Comment by fatwang2** [comment]
你用的是itchat嚒？另外记得重新启动项目

MILKMILKKING ***@***.***>于2023年9月24日 周日23:29写道：

**Comment by MILKMILKKING** [comment]
itchat，我不太清楚这是什么。我是在云电脑的企业微信上运行的。请问你问的是这个吗？
我也再重启一下项目试试。

**Comment by fatwang2** [comment]
那破案了，企业微信目前还不支持，仅支持个人微信

MILKMILKKING ***@***.***>于2023年9月24日 周日23:35写道：

**Comment by MILKMILKKING** [comment]
好吧，谢谢~
那能否开发一下企业微信也用上这个功能？
另外，既然可以总结文章，那能不能总结转发过来的聊天记录（自定义提示词总结）？

**Comment by fatwang2** [comment]
后续迭代计划写在说明文档里了，新需求也可以提

MILKMILKKING ***@***.***>于2023年9月24日 周日23:52写道：

**Comment by MILKMILKKING** [comment]
我在个人微信上成功实现了链接卡片的总结，感谢! 另外，能否新增一个开关，选择是否展示最后的那个详情链接，其实绝大多数也不会去点开那个链接。

**Comment by fatwang2** [comment]
好的，后面会把一些配置项当做参数放开
