### ISSUE TITLE
安装完成后 #scanp无法发现

### ISSUE THREAD

**Issue by CyrilTang** [fatwang2/sum4all#30]
Docker部署的项目，通过管理员安装
[INFO]
安装插件成功，请使用 #scanp 命令扫描插件或重启程序，开启前请检查插件是否需要配置

[INFO]
插件扫描完成, 未发现新插件

**Comment by fatwang2** [comment]
能否贴一下你的报错日志？

**Comment by MrSleeplessC** [comment]
报错信息 Failed to import plugin sum4all: No module named 'docx'

**Comment by MrSleeplessC** [comment]
恩。执行了一遍 pip3 install -r requirements.txt  ，搞定！
