### ISSUE TITLE
各种类型的总结都无法成功

### ISSUE THREAD

**Issue by MrSleeplessC** [fatwang2/sum4all#32]
📌总结
网络不给力，请稍后重试。

💡要点
1️⃣ 网络出现故障，导致无法连接。🚫
2️⃣ 可能是网络运营商的问题，也可能是本地网络故障。🛠️
3️⃣ 稍后重试或联系网络运营商解决问题。☎️

💬5min内输入问+问题，可继续追问

**Comment by fatwang2** [comment]
请问你用的是哪个总结服务？
