### ISSUE TITLE
无法在线安装sum4all

### ISSUE THREAD

**Issue by specialvan** [fatwang2/sum4all#33]
![image](https://github.com/fatwang2/sum4all/assets/59273632/60bc93a2-97fe-4581-8fff-bf9cdb798e51)
![image](https://github.com/fatwang2/sum4all/assets/59273632/3940546e-c241-4ed0-a502-c143ac75b07c)
本地无法在线安装sum4all，只能用docker部署的方式？

**Comment by fatwang2** [comment]
可以安，你这不是提示已经存在了，你按照操作步骤配置文件重启 cow

**Comment by specialvan** [comment]
我换成了gitee的地址,成功安装了插件.但是按文档说明无法调用perpelxity模型的接口,默认还是chatgpt.是否要在chatgpt-on-wechat的config.json下新增一个bot,说明用的是perpelxity模型?
![image](https://github.com/fatwang2/sum4all/assets/59273632/b77a6ed8-5203-471f-99cf-6b5d2d1d17ea)

**Comment by fatwang2** [comment]
你不用自由发挥，插件很多人正在用，没有什么需要额外做的事情，按照要求安装，配置插件的配置文件，不需要动主程序的配置文件，你日志里根本没走插件

**Comment by fatwang2** [comment]
你可以plist一下，我看你现在好像根本没有安装成功

**Comment by Quuuquu** [comment]
安装报错，扫描不出来
![微信截图_20240419141605](https://github.com/fatwang2/sum4all/assets/106719312/2adaadfe-156a-412b-a568-4bba32c6ab7a)
![微信截图_20240419141627](https://github.com/fatwang2/sum4all/assets/106719312/8bf3d463-e873-42bc-b018-aa36a2a45515)
![微信截图_20240419141639](https://github.com/fatwang2/sum4all/assets/106719312/778e8bcb-545a-4b97-a4d1-728b809e6051)

**Comment by fatwang2** [comment]
你是怎么安装的呢？
