### ISSUE TITLE
总结微信文章一直报错呀

### ISSUE THREAD

**Issue by starsliao** [fatwang2/sum4all#34]
<img width="952" alt="6dcb28de139f6f0eae7d8c8d506b709" src="https://github.com/fatwang2/sum4all/assets/3349611/72d16a4b-45d1-40c6-8396-9bc4e24e7561">

我配置了openai 为啥还要连接http://ai.sum4all.site/

**Comment by fatwang2** [comment]
因为 opneai 不会帮你爬取内容，调接口是爬取的。报错的话，你检查下你的配置文件

**Comment by hanfangyuan4396** [comment]
> 因为 opneai 不会帮你爬取内容，调接口是爬取的。报错的话，你检查下你的配置文件

把api key直接给sum4all可以不

**Comment by fatwang2** [comment]
没懂，你要不加 telegram 频道聊。你选不同的总结服务要填写不同的 key，GitHub 说明里有讲

Han Fangyuan ***@***.***>于2024年1月29日 周一20:26写道：
