### ISSUE TITLE
飞书如何在群内不用@机器人就自动总结ile和url

### ISSUE THREAD

**Issue by autherlj** [fatwang2/sum4all#37]
你好，请教一下我飞书客户端如果私聊bot则可以自动分析
![image](https://github.com/fatwang2/sum4all/assets/30717333/24a10dde-705d-4867-9319-bf8ff5ba8be7)
但是如果bot在群内，就必须要@bot才可以，请问如何像linkai里面一样，在群里的时候发url和文件就不用@bot就可以自动分析，我看了config.json里面的group开关，改成false也没效果。

**Comment by fatwang2** [comment]
群消息我没有加前缀词，理论上是可以自动识别的，方便的话，你添加项目的 telegram频道，晚上我找你调试下看看

**Comment by fatwang2** [comment]
请问是问题解决了吗

Autherlj ***@***.***>于2024年3月11日 周一14:10写道：
