### ISSUE TITLE
docker下安装插件异常

### ISSUE THREAD

**Issue by cype62** [fatwang2/sum4all#41]
<img width="1265" alt="image" src="https://github.com/fatwang2/sum4all/assets/37395207/0d125581-9206-4cd0-beda-32656a64054d">
在chatgpt-on-wechat的docker里面，安装的时候出现权限问题。
我进入容器里面直接执行pip install --user -r ……能装完依赖，但#scanp的时候，docker容器依然报找不到一些命令
<img width="1113" alt="image" src="https://github.com/fatwang2/sum4all/assets/37395207/ad13cba6-02d5-4c4a-9bff-f83fc5642b3e">

**Comment by fatwang2** [comment]
升级下Python 版本看看，这个 docx 在依赖里有

**Comment by cype62** [comment]
找到问题了，自动安装的时候，容器里面pip有些依赖放到了noroot的路径下，而加载依赖读取路径是全局路径
