### ISSUE TITLE
打扰一下，有一个sum4all的数据保存问题请教您一下。

### ISSUE THREAD

**Issue by Minstrel-Pal** [fatwang2/sum4all#44]
我是用docker安装的chatgpt-on-wechat，用#installp https://github.com/fatwang2/sum4all.git，这个方式安装的sum4all插件，在我用docker rm *  删除掉容器后插件也会删除，有没有什么办法能把下载的插件映射到本地文件夹，这样就不会丢失了。

**Comment by fatwang2** [comment]
你看我部署方式那里，关于 docker 部署有一个持久化的方式

**Comment by Minstrel-Pal** [comment]
十分感谢
