### ISSUE TITLE
实现与文件或链接内容进行多轮对话的功能

### ISSUE THREAD

**Issue by MILKMILKKING** [fatwang2/sum4all#6]
chatgpt-on-wechat的linkai已经实现了进一步可以与文件或链接的内容进行多轮对话的功能。
咱们是否也能跟进这项能力？

linkai说明文档：
https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins/linkai#3%E6%96%87%E6%A1%A3%E6%80%BB%E7%BB%93%E5%AF%B9%E8%AF%9D%E5%8A%9F%E8%83%BD

**Comment by fatwang2** [comment]
看到了，自己体验了下，这个场景实际使用感受并不好，你可以先用linkai的企业微信体验下

MILKMILKKING ***@***.***>于2023年9月27日 周三18:03写道：
