### ISSUE TITLE
建议更新GPT-4o为视图模型，建议增加聊天总结功能

### ISSUE THREAD

**Issue by mingtian886** [fatwang2/sum4all#60]
建议更新GPT-4o为视图模型，毕竟便宜一些，效果也还行
建议增加聊天总结功能，最近这个呼声很高，也切合大佬的开发计划

**Comment by fatwang2** [comment]
gpt-4o 今天支持下，聊天总结暂时没精力，欢迎 pr

mingtian ***@***.***>于2024年6月2日 周日12:43写道：

**Comment by fatwang2** [comment]
gpt-4o已更新
