### ISSUE TITLE
想注册pro.sum4all.site 看看怎么购买，但说“关闭了密码注册”

### ISSUE THREAD

**Issue by bingjiw** [fatwang2/sum4all#62]
想注册pro.sum4all.site 看看怎么购买，但说“关闭了密码注册”，叫人家买，又不让人注册

**Comment by fatwang2** [comment]
支持 GitHub 注册呀

bingjiw ***@***.***>于2024年6月3日 周一13:38写道：

**Comment by tmw10100727** [comment]
现在用github,sum4ll出现：注意，此处生成的令牌用于系统管理，而非用于请求 OpenAI 相关的服务。是不能用API调用了吗
