### ISSUE TITLE
gemini模型能不能更新到最新的gemini-1.5-pro-latest模型?

### ISSUE THREAD

**Issue by longxingdeng** [fatwang2/sum4all#70]
目前使用的gemini-pro模型图像识别能力不太行，对文字识别效果比较差，
![1719983590224](https://github.com/fatwang2/sum4all/assets/134866140/8623dcdf-c737-489b-b979-c989e99dfeff)
大一点的图直接出错
![image](https://github.com/fatwang2/sum4all/assets/134866140/5194b95a-4707-44cb-ba09-0cf5a520c32f)

**Comment by 66Cjj** [comment]
想使用Gemini的key，配置表是这样设置吗？我一直报401
![Uploading c3f44ab953dc0a9e4fc12558be9e982.png…]()

**Comment by fatwang2** [comment]
更新为Gemini 1.5 Flash了
