### ISSUE TITLE
能否用 免费的Gemini Flash 代替 Gemini Pro 做图片等的总结？

### ISSUE THREAD

**Issue by bingjiw** [fatwang2/sum4all#81]
发现sum4all的代码(如下)中是使用gemini-pro-vision做图片识别的，能否用免费的Gemini Flash 1.5 代替 pro 呢？

`        elif self.image_sum_service == "gemini":
            api_key = self.gemini_key
            api_base = "https://gemini.sum4all.site/v1/models/gemini-pro-vision:generateContent"`

**Comment by fatwang2** [comment]
Gemini 1.5 Flash不是免费的吧？

**Comment by fatwang2** [comment]
我更新为Gemini 1.5 Flash了

**Comment by CatByteDance** [comment]
> 我更新为Gemini 1.5 Flash了

个人使用完全是够的吧
![image](https://github.com/user-attachments/assets/9bfc19ee-4218-4d13-8e57-a8dc991272d2)

**Comment by fatwang2** [comment]
对
