### ISSUE TITLE
用Gemini识图时，报错：Not Found for url: https://gemini.sum4all.site/v1/models/gemini-pro-vision:generateContent

### ISSUE THREAD

**Issue by bingjiw** [fatwang2/sum4all#82]
https://gemini.sum4all.site/v1/models/gemini-pro-vision:generateContent

![Screenshot 2024-08-31 at 09 57 49](https://github.com/user-attachments/assets/8a211288-ccd9-467e-a773-8acd53b0417a)

Not Found for url: https://gemini.sum4all.site/v1/models/gemini-pro-vision:generateContent

是否把链接URL改为Google Gemini的直接链接，就能解决问题？

**Comment by bingjiw** [comment]
是否你 反向代理Google的gemini.sum4all.site 已经DOWN，或没启动？在马来西亚 还需要用你的反向代理吗？

**Comment by fatwang2** [comment]
新版本把代理去掉了，可以试试
