### ISSUE TITLE
这是什么情况

### ISSUE THREAD

**Issue by rexinshimin0001** [fatwang2/sum4all#89]
![Screenshot_2024-09-12-09-15-53-723_com.tencent.mm.png](https://github.com/user-attachments/assets/4225e8f4-783a-4ac3-8538-402db9217af6)

是这个问题涉及到什么么，搜其他的都可以

**Comment by fatwang2** [comment]
能别瞎搞吗

**Comment by rexinshimin0001** [comment]
没瞎搞啊，就是简单的搜新闻，发现的问题然后搜其他问题都可以，就这个问题搜不了> 能别瞎搞吗
