### ISSUE TITLE
为啥handle url是把api base和key发到你的网址？https://ai.sum4all.site

### ISSUE THREAD

**Issue by spacex-3** [fatwang2/sum4all#90]
api_url = "https://ai.sum4all.site"
            response = requests.post(api_url, headers=headers, data=payload)
            response.raise_for_status()
            logger.info('Received response from LLM.')
            response_data = response.json()  # 解析响应的 JSON 数据
            if response_data.get("success"):
                content = response_data["content"].replace("\\n", "\n")  # 替换 \\n 为 \n
                self.params_cache[user_id]['content'] = content

                # 新增加的部分，用于解析 meta 数据
                meta = response_data.get("meta", {})  # 如果没有 meta 数据，则默认为空字典
                title = meta.get("og:title", "")  # 获取 og:title，如果没有则默认为空字符串
                self.params_cache[user_id]['title'] = title
                # 只有当 title 非空时，才加入到回复中
                if title:
                    additional_content += f"{title}\n\n"
                reply_content = additional_content + content  # 将内容加入回复
                
            else:
                reply_content = "Content not found or error in response"

        except requests.exceptions.RequestException as e:
            # 处理可能出现的错误
            logger.error(f"Error calling new combined api: {e}")
            reply_content = f"An error occurred"

**Comment by fatwang2** [comment]
因为我把爬取和 AI 的逻辑抽出来做了个接口，可以翻最开始的版本是全部在插件代码里的，代码量比较大，也会暴露我自己的爬取服务。如果担心泄露问题大可不必，你用的所有三方代理如果想拿的话都可以拿到你的 key

**Comment by spacex-3** [comment]
> 因为我把爬取和 AI 的逻辑抽出来做了个接口，可以翻最开始的版本是全部在插件代码里的，代码量比较大，也会暴露我自己的爬取服务。如果担心泄露问题大可不必，你用的所有三方代理如果想拿的话都可以拿到你的 key

嗯嗯不是担心泄漏，就是今天在看代码结构学习的时候觉得奇怪。
用肯定还是继续用的。晚点我学习一下你最开始的版本谢谢啦！

**Comment by fatwang2** [comment]
主要是一旦我把爬取服务暴露出来，别人就可以不用走插件，自己在其他地方调用，爬虫服务器的成本却是我来承担。除非我把这部分也彻底商业化，需要传入我的 key 才能用这个爬取服务

**Comment by spacex-3** [comment]
> 主要是一旦我把爬取服务暴露出来，别人就可以不用走插件，自己在其他地方调用，爬虫服务器的成本却是我来承担。除非我把这部分也彻底商业化，需要传入我的 key 才能用这个爬取服务

是的，我本来想着说自己爬一下，但是发现也麻烦，还是继续用您的服务，再次感谢大佬啦！
