### ISSUE TITLE
搜索功能无法正常使用 An error occurred

### ISSUE THREAD

**Issue by AcidGr** [fatwang2/sum4all#93]
Error calling new combined api: 500 Server Error: Internal Server Error for url: https://ai.sum4all.site/

**Comment by fatwang2** [comment]
可以检查下配置

AcidGr ***@***.***>于2024年9月24日 周二18:24写道：

**Comment by AcidGr** [comment]
在今天上午之前都能正常使用，下午好像收到了大量的访问请求后用不了了，是不是被ban了

**Comment by AcidGr** [comment]
在今天上午之前都能正常使用，下午好像收到了大量的访问请求后用不了了，是不是被ban了

**Comment by fatwang2** [comment]
我试了下，没问题，你用什么模型，什么服务，看看额度还有吗？

AcidGr ***@***.***>于2024年9月24日 周二18:36写道：

**Comment by AcidGr** [comment]
嗯，没问题了。是额度用完了
