### ISSUE TITLE
这是什么问题，帮忙看看

### ISSUE THREAD

**Issue by vsd269** [fatwang2/sum4all#94]
![f1206c62c0c45f641aeee9a25983919](https://github.com/user-attachments/assets/f12e3713-e56c-47ad-9a45-d2fba32ea921)

**Comment by fatwang2** [comment]
是之前可以用，现在突然不可以了，还是一直没有成功？如果是后者，检查下配置。如果是前者，发不同的链接试试

**Comment by vsd269** [comment]
之前可以用，都好好的。最近就突然不能用，配置我发你看下
![image](https://github.com/user-attachments/assets/a6349d1d-d9bd-4a77-8234-9bec5de2bf1c)

**Comment by vsd269** [comment]
之前可以用的，最近就突然没法用了。你看下我的配置
![微信截图_20241006230655](https://github.com/user-attachments/assets/e630ef82-20d8-464f-9996-79cbe7a15ded)

**Comment by fatwang2** [comment]
你现在这么配置，上面选的是 sum4all 的 service 吗？你的 key 还有余额吗

**Comment by vsd269** [comment]
![image](https://github.com/user-attachments/assets/b11f1403-2530-47f6-a40d-f2d3fe16bb5c)
有余额的，才充的

**Comment by vsd269** [comment]
有空帮忙看看，谢谢啦

**Comment by fatwang2** [comment]
国庆在外面玩，等我回去的
vsd269 ***@***.***>于2024年10月8日 周二11:26写道：

**Comment by fatwang2** [comment]
已经修复啦！是我自己的key额度用完了，刚充值了下就好了，你再试试

**Comment by vsd269** [comment]
可以了，还得依赖你那边额度才能跑通么，为什么我看其他人正常
